license="${mod_license}"
issueTrackerURL="https://github.com/montoyo/webdisplays/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://montoyo.net/wd2.php"
credits="Thanks to sadreminderwindows for the Chinese translation. Thanks to binary1230 for the ComputerCraft support."
authors="montoyo"
description='''
Web Screens! Yayyy!!
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mcef"
    type="required"
    reason="WebDisplays renders screens using MCEF's Chromium browser texture"
    versionRange="[2.1.6-26.2-SNAPSHOT,)"
    ordering="AFTER"
    side="CLIENT"
